package com.tangguna.rxhttputils.rxhttputils;



public class Users {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.id
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.account
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	private String account;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.password
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.nick
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	private String nick;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.realname
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	private String realname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.provinceid
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	private Integer provinceid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.cityid
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	private Long cityid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.districtid
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	private Long districtid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.roleid
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	private Integer roleid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.registertime
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	private Long registertime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.lastlogin
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	private Long lastlogin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.accesstoken
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	private String accesstoken;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.tokents
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	private Long tokents;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.id
	 * @return  the value of users.id
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.id
	 * @param id  the value for users.id
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.account
	 * @return  the value of users.account
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.account
	 * @param account  the value for users.account
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	public void setAccount(String account) {
		this.account = account == null ? null : account.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.password
	 * @return  the value of users.password
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.password
	 * @param password  the value for users.password
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.nick
	 * @return  the value of users.nick
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	public String getNick() {
		return nick;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.nick
	 * @param nick  the value for users.nick
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	public void setNick(String nick) {
		this.nick = nick == null ? null : nick.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.realname
	 * @return  the value of users.realname
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	public String getRealname() {
		return realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.realname
	 * @param realname  the value for users.realname
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	public void setRealname(String realname) {
		this.realname = realname == null ? null : realname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.provinceid
	 * @return  the value of users.provinceid
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	public Integer getProvinceid() {
		return provinceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.provinceid
	 * @param provinceid  the value for users.provinceid
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	public void setProvinceid(Integer provinceid) {
		this.provinceid = provinceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.cityid
	 * @return  the value of users.cityid
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	public Long getCityid() {
		return cityid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.cityid
	 * @param cityid  the value for users.cityid
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	public void setCityid(Long cityid) {
		this.cityid = cityid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.districtid
	 * @return  the value of users.districtid
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	public Long getDistrictid() {
		return districtid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.districtid
	 * @param districtid  the value for users.districtid
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	public void setDistrictid(Long districtid) {
		this.districtid = districtid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.roleid
	 * @return  the value of users.roleid
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	public Integer getRoleid() {
		return roleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.roleid
	 * @param roleid  the value for users.roleid
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	public void setRoleid(Integer roleid) {
		this.roleid = roleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.registertime
	 * @return  the value of users.registertime
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	public Long getRegistertime() {
		return registertime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.registertime
	 * @param registertime  the value for users.registertime
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	public void setRegistertime(Long registertime) {
		this.registertime = registertime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.lastlogin
	 * @return  the value of users.lastlogin
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	public Long getLastlogin() {
		return lastlogin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.lastlogin
	 * @param lastlogin  the value for users.lastlogin
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	public void setLastlogin(Long lastlogin) {
		this.lastlogin = lastlogin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.accesstoken
	 * @return  the value of users.accesstoken
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	public String getAccesstoken() {
		return accesstoken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.accesstoken
	 * @param accesstoken  the value for users.accesstoken
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	public void setAccesstoken(String accesstoken) {
		this.accesstoken = accesstoken == null ? null : accesstoken.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.tokents
	 * @return  the value of users.tokents
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	public Long getTokents() {
		return tokents;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.tokents
	 * @param tokents  the value for users.tokents
	 * @mbg.generated  Thu Jun 28 09:33:13 CST 2018
	 */
	public void setTokents(Long tokents) {
		this.tokents = tokents;
	}


	
}